### PR TITLE
Fix #2078: AJP throws NPE for responses larger than 8192 bytes

### LINKED ISSUE #2078: AJP throws NPE for responses larger than 8192 bytes
When using AJP between an Apache webserver and GlassFish, GlassFish throws a NullPointerException after writing the response chunks for a request, instead of sending an AJP END_RESPONSE packet. This only happens when the response body is larger than 8192 bytes.

Increasing the send buffer size of the AJP listener (which defaults to 8192 bytes) doesn't make any difference.

```
java.lang.NullPointerException
        at org.glassfish.grizzly.http.ajp.AjpHandlerFilter.encodeHttpPacket(AjpHandlerFilter.java:258)
        at org.glassfish.grizzly.http.ajp.AjpHandlerFilter.handleWrite(AjpHandlerFilter.java:221)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:87)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:866)
        at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:834)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1068)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushBinaryBuffers(OutputBuffer.java:1042)
        at org.glassfish.grizzly.http.io.OutputBuffer.flushAllBuffers(OutputBuffer.java:1012)
        at org.glassfish.grizzly.http.io.OutputBuffer.close(OutputBuffer.java:730)
        at org.glassfish.grizzly.http.io.OutputBuffer.endRequest(OutputBuffer.java:377)
        at org.glassfish.grizzly.http.server.Response.finish(Response.java:518)
        at org.glassfish.grizzly.http.server.HttpServerFilter.afterService(HttpServerFilter.java:373)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:243)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
```

I reported this as a GlassFish bug two years ago (https://github.com/eclipse-ee4j/glassfish/issues/22295), but nothing was even done with my report. Because it's possible to work around the bug by patching Grizzly, I'm reporting the bug here. (even though I'm not sure it's in fact a bug in Grizzly; it's also possible that GlassFish is using Grizzly in a way it shouldn't)

### PR DESCRIPTION
**Pull request by omolenkamp**

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
Hi @omolenkamp , could you rebase the PR, please?

**Comment by javierllorente** [comment]
It has been almost a month since you asked @omolenkamp. So I have signed the ECA and rebased his fix.
Pull request https://github.com/eclipse-ee4j/grizzly/pull/2132

**Comment by dmatej** [comment]
This PR can be closed.

**Comment by mnriem** [comment]
@arjantijms Can you please close this one out?

**Pull request closed without merging**
