### PR TITLE
Jakarta EE namespace transition

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by smillidge** [comment]
Probably needs a version bump to 3.0.0 in the poms.

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Test failure is on `java.net.BindException: Address already in use`

**Comment by arjantijms** [comment]
I have the same of similar issue on master:

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.glassfish.grizzly.connectionpool.SingleEndPointPoolTest
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 23.293 s <<< FAILURE! - in org.glassfish.grizzly.connectionpool.SingleEndPointPoolTest
[ERROR] testConnectionTTL(org.glassfish.grizzly.connectionpool.SingleEndPointPoolTest)  Time elapsed: 0.003 s  <<< ERROR!
java.net.BindException: Address already in use
	at org.glassfish.grizzly.connectionpool.SingleEndPointPoolTest.init(SingleEndPointPoolTest.java:83)
```

Maybe that test is a little flaky?

**Comment by jGauravGupta** [comment]
Thanks @arjantijms for fixing the Grizzly test.

**Pull request merged**
