### PR TITLE
fix invalid loop counter increment in Buffers#put

### PR DESCRIPTION
**Pull request by kofemann**
Detected by static code analysis

### CODE REVIEW

**Review by dmatej — APPROVED** [review]
This is a really crazy mistake. What does it affect? It seems to me it should be visible error somehow ...

**Review by MattGill98 — APPROVED** [review]
Looks like a bit of an oversight to say the least, thanks for the PR!

**Review by MattGill98 — CHANGES_REQUESTED** [review]
Just spotted the copyright header, needs updating to 2020

**Comment by MattGill98** [comment]
Thank you, looks good!

**Review by MattGill98 — APPROVED** [review]

**Pull request merged**
