### PR TITLE
Merge 3.0.0 release in master

### PR DESCRIPTION
**Pull request by arjantijms**

### CODE REVIEW

**Review by dmatej — APPROVED** [review]
Don't forger to update the BOM too! :-)
Local build passed with JDK8.

**Review by m0mus — CHANGES_REQUESTED** [review]
Please update copyright years.

**Comment by arjantijms** [comment]
> Please update copyright years.

The commit says: "committed on 23 Nov 2020"

So wouldn't it need to be merged in as-is, as those changes were made then?

**Comment by arjantijms** [comment]
Since I can't edit a PR from another branch directly, I'm closing this, will prepare a 3.0.1 in another branch, and do a PR from that.

**Comment by dmatej** [comment]
If I remember well, copyright year declares year when the code was created and the copyright license covers the change since that date. So I don't think it is required to change the date, I would even expect it is a wrong idea. Or am I wrong?

**Comment by m0mus** [comment]
I didn't see that this PR is old. I approve it. But it's already closed...

**Pull request closed without merging**
