### PR TITLE
Abort filter chain if SSL connection closed

### PR DESCRIPTION
**Pull request by MattGill98**
This will prevent endless loops if the SSL connection is terminated early without enough data.

I struggled to create a programmatic test for this as it's a race condition.

### CODE REVIEW

**Review by Cousjava — APPROVED** [review]

**Comment by arjantijms** [comment]
@MattGill98 There's some errors here regarding the following:

```
[ERROR] testSimplePendingSSLClientWrites[0](org.glassfish.grizzly.SSLTest)  Time elapsed: 0.002 s  <<< ERROR!
java.net.BindException: Address already in use
	at org.glassfish.grizzly.SSLTest.doTestPendingSSLClientWrites(SSLTest.java:619)
	at org.glassfish.grizzly.SSLTest.testSimplePendingSSLClientWrites(SSLTest.java:221)
```

**Comment by MattGill98** [comment]
The errors are present on master too I believe!

**Comment by bshannon** [comment]
If you can show that the "Address already in use" error is there on master, file a
separate bug for and and then I think we should approve this PR assuming it
solves the original problem.

It ought to be possible to insert a filter in there somewhere that can terminate the
connection early to induce the error.

**Comment by MattGill98** [comment]
@arjantijms is this good to merge now?

**Comment by MattGill98** [comment]
@arjantijms can this be merged??

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
