### PR TITLE
Fixes for OSGi environment

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
You beat me to it. LGTM!

**Comment by senivam** [comment]
I had to add -Pstaging to the build configuration (this can be reverted later) due to jakarta.ws.rs (3.0.0). dependency which is still in staging only.

**Comment by senivam** [comment]
actually I had to revert `-Pstaging` back because it appears to be useless - build starts from somewhere else. So, build on Travis will fail untill jakarta.ws.rs is in central. But since release (in Jenkins) is being done using `-Pstaging` profile it could be released before publishing jakarta.ws.rs to central...

**Comment by arjantijms** [comment]
> I had to add -Pstaging to the build configuration (this can be reverted later) due to jakarta.ws.rs (3.0.0). dependency which is still in staging only.

This should already have been pushed out to Maven central.  @spericas can you push the staged artefact out?

**Comment by arjantijms** [comment]
ps jakarta.ws.rs 3.0.0 is on maven central

**Pull request merged**
