### PR TITLE
Setting localMaxConcurrentStreams from configuration and calculate highwate…

### LINKED ISSUE #2036: Http2AddOn ignores maxConcurrentStreams setting (uses hard coded value of 100)
The setting for maxConcurrentStreams via 

    final Http2AddOn http2AddOn = new Http2AddOn(
        Http2Configuration.builder().maxConcurrentStreams(10).build()
    );
    networkListener.registerAddOn(http2AddOn);
    httpServer.addListener(networkListener);
    httpServer.start();

has no effect. Instead, `org.glassfish.grizzly.http2.Http2Session#getDefaultMaxConcurrentStreams` is always used (hard coded to a value of 100).

This has two effects:

1. The server sends a GOAWAY frame (ErrorCode.REFUSED_STREAM) after a fixed number of 100 concurrent streams are exceeded
2. The server never sends a SETTINGS frame for SETTINGS_MAX_CONCURRENT_STREAMS

Version: grizzly-http2 2.4.4, grizzly-http-server 2.4.4

### PR DESCRIPTION
**Pull request by svendiedrichsen**
…r mark. Some additional import reorganization done.

Fixes #2036 

Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
@Chris-Lercher Would you mind confirming this fix?

**Review by Chris-Lercher — CHANGES_REQUESTED** [review]
Setting the high watermark correctly is probably a good idea, but the problem remains: An Http2SessionException is thrown in line 1006:
```java
if (concurrentStreamsCount >= getLocalMaxConcurrentStreams()) {
                // throw Session level exception because headers were not decompressed,
                // so compression context is lost
    throw new Http2SessionException(ErrorCode.REFUSED_STREAM);
```
My debugger tells me, that getLocalMaxConcurrentStreams() is still fixed to 100.

**Comment by svendiedrichsen** [comment]
@Chris-Lercher Sorry, I misread your bug report. I have moved the code to initialize the `localMaxConcurrentStreams` into the constructor. Please have a look.

**Review by Chris-Lercher — APPROVED** [review]
It works fine now! The server now sends the max concurrent streams value in the SETTINGS frame correctly, and it also allows the number of concurrent streams without throwing an Http2StreamException. (Note: I did not review the code changes, as I am not familiar with Grizzly's source code)

**Comment by smillidge** [comment]
Hi @svendiedrichsen, 

Is it possible to add a test to verify that this is being set correctly?

**Comment by svendiedrichsen** [comment]
Sure. I will add a test.

**Comment by svendiedrichsen** [comment]
@smillidge Added a unit test to assert the value is set correctly and resolved the code conflict.

**Review by smillidge — APPROVED** [review]

**Comment by smillidge** [comment]
@MattGill98 do you want to take a look

**Review by MattGill98 — COMMENTED** [review]
Like these changes! Just for completeness, I think this would benefit from a similar test for the 
localStreamWindowSize as well?

**Comment by svendiedrichsen** [comment]
I will add some tests for the window size.
> Like these changes! Just for completeness, I think this would benefit from a similar test for the
> localStreamWindowSize as well?

**Comment by svendiedrichsen** [comment]
@MattGill98 Test added.

**Review by MattGill98 — APPROVED** [review]
Nice, LGTM!

**Pull request merged**
