### PR TITLE
(#2034) Fixing double servlet initialization

### LINKED ISSUE #2034: WebappContext.setLoadOnStartup does not work as advertised (bug?) (servlet is created twice)
setting loadOnStartup will create the servlet on startup at:

https://github.com/eclipse-ee4j/grizzly/blob/30609402b13c7c965ceb5df69a69ccd58d8c85c5/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java#L1883

however, this instance is not being set into the holder at:

https://github.com/eclipse-ee4j/grizzly/blob/30609402b13c7c965ceb5df69a69ccd58d8c85c5/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java#L1891

resulting in the servlet being instantiated again on first request.

as a workaround I am using:

```
package org.glassfish.grizzly.servlet;

import javax.servlet.Servlet;

public final class FixedWebappContext extends WebappContext {

  public FixedWebappContext(String displayName) {
    super(displayName);
  }

  public FixedWebappContext(String displayName, String contextPath) {
    super(displayName, contextPath);
  }

  public FixedWebappContext(String displayName, String contextPath, String basePath) {
    super(displayName, contextPath, basePath);
  }

  @Override
  protected Servlet createServletInstance(ServletRegistration registration) throws Exception {
    Servlet srvlet = super.createServletInstance(registration);
    registration.servlet = srvlet;
    return srvlet;
  }
}
```

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Fixes #2034 

Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>

### CODE REVIEW

**Comment by smillidge** [comment]
Is there also a test that is appropriate to add to prevent a regression?

**Comment by svendiedrichsen** [comment]
Sure. I will add a test.

**Comment by MattGill98** [comment]
I like these changes, but before it can be merged you'll need to sign the ECA. See https://accounts.eclipse.org/user/eca.

**Comment by svendiedrichsen** [comment]
I had aleady done that. 
Bildschirmfoto 2020-01-30 um 20 50 35

**Comment by MattGill98** [comment]
Hmm is it the same email as in your signed-off footer? The license check still seems to be failing. If you're sure it should have worked, you could try force pushing something like a commit message change to the last commit

**Comment by pzygielo** [comment]
Merge commit 0ccaa552d09a5c19a4c033b30924ea0e8a0e8a62 has no S-O footer. Consider rebasing your two commits on current master. (Or edit comment in merge commit.)

**Comment by svendiedrichsen** [comment]
I have singed off my latest commit and merged in the master but there were test failures in the travis build. 
The error was `java.net.BindException: Address already in use`. Looks like a pretty common problem with the builds. At least the eca check was good.

**Review by MattGill98 — APPROVED** [review]

**Comment by svendiedrichsen** [comment]
Thank you.

**Comment by bshannon** [comment]
Why was this merged if there were test failures?  Is this test known to be buggy?
Is someone working on fixing the buggy test?

**Pull request merged**
