### PR TITLE
Aggregated fixes from Payara

### LINKED ISSUE #2016: Async servlet failed to send large data frames completely when HTTP/2 trailers are present
I tried to let a async servlet send out a sequence of large data (40k each) followed by trailers. The client does receive the trailer, but only receives partial data.

- This issue does not happen **if I use Undertow 2.0.12 instead of Glassfish 5.0**.
- The issue also does not happen **if I `Thread.sleep` for 100ms** (the shorter the time is, the more flaky the result will be) before `asyncContext.complete()`
- This issue also does not happen **if only sending out a few bytes**.
- The servlet will send out data frames completely **if I do not send trailers**.

### Steps to reproduce:
1. Deploy the following servlet with glassfish 5.0
```java
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Supplier;
import javax.servlet.AsyncContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.WriteListener;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = {"/large_output_with_trailer"}, asyncSupported = true)
public class LargeOutputWithTrailer extends HttpServlet {
  @Override
  protected void doGet(HttpServletRequest req, HttpServletResponse resp)
      throws IOException {
    AsyncContext asyncCtx = req.startAsync();

    resp.setStatus(HttpServletResponse.SC_OK);
    resp.setContentType("application/binary");
    resp.setHeader("trailers", "hello");

    final TrailerSupplier trailerSupplier = new TrailerSupplier();
    resp.setTrailerFields(trailerSupplier);
    resp.flushBuffer();

    final ServletOutputStream outputStream = resp.getOutputStream();
    outputStream.setWriteListener(new WriteListener() {
      int i;

      @Override
      public void onWritePossible() throws IOException {

        System.out.println("onWritePossible");
        while (outputStream.isReady()) {
          if (i < 3) {
            byte[] bytes = new byte[40000];
            outputStream.write(bytes);
            i++;
          } else {
            // Allow more time to let buffer clear out can workaround the issue
            // try {
            //   Thread.sleep(100);
            // } catch (InterruptedException e) {
            // }

            System.out.println("set trailers");
            trailerSupplier.get().put("hello", "world");
            System.out.println("complete");
            asyncCtx.complete();
            return;
          }
        }

        System.out.println("not ready");
      }

      @Override
      public void onError(Throwable t) {
        t.printStackTrace();
      }
    });
  }

  private static final class TrailerSupplier implements Supplier<Map<String, String>> {
    final Map<String, String> trailers = new ConcurrentHashMap<>();

    @Override
    public Map<String, String> get() {
      return trailers;
    }
  }
}
```

2. Run [HTTP/2 client](https://github.com/http2/http2-spec/wiki/Tools) to send a POST request
```
nghttp "http://localhost:8080/large_output_with_trailer" -v
```

Console output:
```
[  2.445] recv DATA frame <length=16383, flags=0x00, stream_id=13>
[  2.445] recv DATA frame <length=16383, flags=0x00, stream_id=13>
[  2.445] recv DATA frame <length=7234, flags=0x00, stream_id=13>
[  2.445] recv DATA frame <length=16383, flags=0x00, stream_id=13>
[  2.445] recv DATA frame <length=9152, flags=0x00, stream_id=13>
[  2.445] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=40000)
[  2.445] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=13>
          (window_size_increment=40000)
[  2.446] recv DATA frame <length=14465, flags=0x00, stream_id=13>
[  2.455] recv DATA frame <length=16383, flags=0x00, stream_id=13>
[  2.456] recv DATA frame <length=9152, flags=0x00, stream_id=13>
[  2.456] recv (stream_id=13) hello: world
[  2.456] recv HEADERS frame <length=11, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
          (padlen=0)
[  2.456] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])

```

3. Sum up the lengths of DATA frames the client received:
   Only `105535` bytes were received, expecting `120000` bytes to be received.
  If you try multiple times, occasionally the client can receive all the `120000` bytes, but it's rare.

### PR DESCRIPTION
**Pull request by dmatej**
Fixes #2016 and #2111

This is a aggregated PR of Payara's fork of 2.4.4, I hope I didn't skip anything.
Current Payara 5.2020.7-SNAPSHOT with these commits in it's own patch of Grizzly passed following tests:

- all Grizzly's own tests
- all Payara's own tests
- TCK - websockets
- TCK - servlet
- my private test using arquillian and Apache HTTP Client and customized reproducer from #2016 
- HTTP/2 Push reproducer "100 Delphines" (after reconfiguring Payara a bit to use 100 threads for HTTP or more)
  - note - this test causes exceptions with Firefox (remote stream reset), but no exceptions on Chrome

### Merge:

* these changes were based on changes done in #2103 , which should be merged first. I will resolve conflicts after that.

### CODE REVIEW

**Comment by dmatej** [comment]
All commits are signed, but eclipsefdn/eca has different opinion - what can I do?

**Comment by edbratt** [comment]
I agree, it does appear you have signed all the commits and you do have a valid ECA. A committer can go ahead and merge, once a review has been completed. 
> 
> 
> All commits are signed, but eclipsefdn/eca has different opinion - what can I do?

**Comment by dmatej** [comment]
I tried even to match my name including czech letters č and ě, but it is still the same. I'm giving up fighting with the eclipsefdn/eca checker ... the PR is prepared to be merged now, I don't plan any other pushes except those which would come from reviews.

**Review by arjantijms — APPROVED** [review]

**Comment by dmatej** [comment]
I rebased the PR, the build will now fail here for two reasons:
* npn is not released yet
* I reenabled AlpnSupportTest, locally tested in following configurations (see npn/openjsse profiles, default is no profile -> using JDK's impl). Travis is using now obsoleted JDK8u151 which does not contain backported ALPN support from newer JDKs yet.

- OpenJDK 8u275, openjsse 1.1.5 ... SUCCESS
- OpenJDK 11.0.8, openjsse 1.1.5 ... FAIL ... as expected
- OpenJDK 8u275, npn bootstrap 1.9 ... FAIL ... as expected
- OpenJDK 8u232, npn bootstrap 1.9.payara-p1 ... SUCCESS
- OpenJDK 8u275 ... SUCCESS
- OpenJDK 11.0.8 ... SUCCESS

**Comment by arjantijms** [comment]
> npn is not released yet

npn is now staged as 2.0.0, which can be used to do the build

**Comment by dmatej** [comment]
The build passed locally with profile -Pstaging now, so after npn will make it to Maven Central it should pass now also on Travis :-)

**Pull request merged**
