### PR TITLE
utils: remove unused version of ThreadLocalRandom

### PR DESCRIPTION
**Pull request by kofemann**
the rest of the code uses java.util.concurrent.ThreadLocalRandom. Thus no reasons tho have a private unused copy ot it.

### CODE REVIEW

**Comment by kofemann** [comment]
ping....

**Comment by mnriem** [comment]
@kofemann Is this PR still relevant?

**Comment by kofemann** [comment]
I think removing dead code is always relevant 😎

**Comment by mnriem** [comment]
@arjantijms Looks good to me

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
