### PR TITLE
Fixes #2122 - Manifests should contain automatic module names

### LINKED ISSUE #2122: Manifests should contain automatic module names

### PR DESCRIPTION
**Pull request by mnriem**

### CODE REVIEW

**Comment by pzygielo** [comment]
Please consider using [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in PR description to have it linked with proper issue.

**Comment by mnriem** [comment]
Fixes #2122

**Comment by pzygielo** [comment]
GH syntax does not allow anything between keyword and issue reference: "Fixes #..."
It has to go to original description (opening comment) to work. Once it does - it will be linked in "Development" section on the right.

**Comment by mnriem** [comment]
@arjantijms What do you think?

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
