### PR TITLE
#1995 Fixed ConcurrentModificationException

### LINKED ISSUE #1995: ConcurrentModificationException in Http2Session.pruneStreams
Hi Team
I observe multiple `ConcurrentModificationException`s thrown from https://github.com/javaee/grizzly/blob/4537e092c3a60557013014f279564fa4877cad29/modules/http2/src/main/java/org/glassfish/grizzly/http2/Http2Session.java#L699-L714
```
GRIZZLY0013: Exception during FilterChain execution
java.util.ConcurrentModificationException
	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1703)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1751)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1745)
	at java.util.AbstractMap$2$1.next(AbstractMap.java:418)
	at org.glassfish.grizzly.http2.Http2Session.pruneStreams(Http2Session.java:709)
	at org.glassfish.grizzly.http2.Http2Session.setGoAwayLocally(Http2Session.java:682)
	at org.glassfish.grizzly.http2.Http2Session.terminate(Http2Session.java:625)
	at org.glassfish.grizzly.http2.Http2BaseFilter.processFrames(Http2BaseFilter.java:212)
	at org.glassfish.grizzly.http2.Http2ServerFilter.handleRead(Http2ServerFilter.java:563)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
```
by Faces application.

S/W Versions
* Grizzly Framework 2.4.1 (GlassFish Server Open Source Edition  5.0  (build 25))
* Mojarra 2.3.2 (GlassFish Server Open Source Edition  5.0  (build 25)) + PrimeFaces 6.1
* OpenJDK Runtime Environment (build 1.8.0_151-b12)

### PR DESCRIPTION
**Pull request by svendiedrichsen**
... when prune finds closed connection.

Fixes #1995 

Please review and advise.

Signed-off-by: Sven Diedrichsen sdiedrichsen@yahoo.de

### CODE REVIEW

**Comment by smillidge** [comment]
This fails IP Validation can you use `git commit -s` to sign off the commit?

**Comment by svendiedrichsen** [comment]
@smillidge I did but it doesn't work. Please see my last commits.

**Review by anajosep — APPROVED** [review]

**Comment by lprimak** [comment]
@svendiedrichsen Do you think this commit possibly fixes 
https://github.com/payara/Payara/issues/2625 and
https://github.com/payara/Payara/issues/3022 ?

I can no longer reproduce the HTTP/2 push issues in Payara, hoping you can definitively shed light on this.

Thank you!

**Comment by lprimak** [comment]
and BTW, hey! These kinds of tough to track down race-condition-y issues are my purview :)

**Comment by lprimak** [comment]
@svendiedrichsen never mind, I can reproduce this issue again.  Will be working on it

**Comment by svendiedrichsen** [comment]
@lprimak sorry for answering late. I'm currently on vacation.

I don't think they are related. There was no concurrency involved here. A single thread simply iterated over a list which it then modified within the loop.

So not really your purview. ;)

**Pull request merged**
